# Generated by Django 4.0.4 on 2022-05-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT')),
                ('dv', models.CharField(max_length=1, verbose_name='Digito Verificador')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('apaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion Cliente')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo Cliente')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Compra')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('Donacion', models.IntegerField(verbose_name='Monto Donado')),
                ('precioNeto', models.IntegerField(verbose_name='Precio Neto Compra')),
                ('precioTotal', models.IntegerField(verbose_name='Precio Total Compra')),
                ('fechaCompra', models.DateField(verbose_name='Fecha de Compra')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Comuna')),
                ('nombreComuna', models.CharField(max_length=50, verbose_name='Nombre Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('stock', models.IntegerField(verbose_name='Stock de Productos')),
                ('valorizacion', models.CharField(max_length=5, verbose_name='Valorizacion del Producto')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion del Producto')),
                ('porcentdesc', models.IntegerField(verbose_name='Porcentaje de Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraceña Usuario')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Pedido')),
                ('fechaPedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('direccionEntrega', models.CharField(max_length=50, verbose_name='Dirección de Entrega')),
                ('estadoEntrega', models.CharField(max_length=50, verbose_name='Estado de la Compra')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha de Entrega')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.comunas')),
                ('idBoleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.compra')),
            ],
        ),
        migrations.CreateModel(
            name='detalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Comprada')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('descuento', models.IntegerField(verbose_name='Porcentaje de Descuento')),
                ('idCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.compra')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.productos')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.comunas'),
        ),
    ]
