# Generated by Django 4.0.4 on 2022-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUser', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraceña Usuario')),
                ('fechainiSesion', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio Sesion')),
            ],
        ),
        migrations.AlterField(
            model_name='compra',
            name='fechaCompra',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fechaEntrega',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fechaPedido',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha del Pedido'),
        ),
    ]
