# Generated by Django 4.0.4 on 2022-05-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_registrosesion_alter_compra_fechacompra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='idBoleta',
            new_name='idcompra',
        ),
    ]
