# Generated by Django 4.0.4 on 2022-05-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_idboleta_pedidos_idcompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='idcompra',
            new_name='idCompra',
        ),
    ]
