# Generated by Django 4.0.5 on 2022-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_idcompra_pedidos_idcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripción del Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='valorizacion',
            field=models.CharField(max_length=5, verbose_name='Valorización del Producto'),
        ),
        migrations.AlterField(
            model_name='registrosesion',
            name='contraseña',
            field=models.CharField(max_length=50, verbose_name='Contraseña Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=50, verbose_name='Contraseña Usuario'),
        ),
    ]
